# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red) "


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 8
truncation_symbol = "…/"

[shell]
fish_indicator = ""
powershell_indicator = "_"
unknown_indicator = "mystery shell"
disabled = false

